### ISSUE TITLE
Have you tried symbolic verson of dm_control envs?

### ISSUE THREAD

**Issue by hnekoeiq** [yusukeurakami/dreamer-pytorch#2]
Hi,
Thanks for the great repo.
I was wondering if you have been able to get results for the dreamer or the planet on symbolic-env version of dm_control tasks?
For me, both dreamer and planet work fine on for example pixel-based reacher-easy but none of them works with symbolic version! Do you know what could be the reason? I tried different encoder-decoder capacity but it still does not learn...  

Thanks in advance for your help.

**Comment by yusukeurakami** [comment]
Hi, @hnekoeiq 
yes I have tried it a little only on walker-walk so not sure it applies to reacher env. From my experience, it will work but it took longer than the image input (took 2M to achieve 900<). In order to make them converge faster, I guess you have to tune the hyperparameters.
