### ISSUE TITLE
Curl Statistics

### ISSUE THREAD

**Issue by michaelzhiluo** [yusukeurakami/dreamer-pytorch#3]
I was wondering how the CURL runs were tracked in order to generate the plots in Readme.md. 

Looking closer into the original pytorch CURL codebase, they log episode reward and step, where step is the number of calls to env.step(). However, the logger does not report the actual # of timesteps taken which is step * action_repeat, which is 2 or 4 as stated in the CURL paper. 

Do the plots reflect this discrepancy?

**Comment by yusukeurakami** [comment]
Thank you for you comment. In order to match the condition, I have tweaked their code to change the definition of step number. For this statistics, step number is what you explained as "step*action_repeat".
