### ISSUE TITLE
AttributeError: ‘TanhBijector’ object has no attribute ‘domain’

### ISSUE THREAD

**Issue by aravindvenu7** [yusukeurakami/dreamer-pytorch#9]
Error when try to execute get_action from actor model.

**Comment by 108618035guotingliao** [comment]
I also met this problem after upgrading pytorch from 1.6 to 1.8.

**Comment by RajGhugare19** [comment]
self.domain = torch.distributions.constraints.real
self.codomain = torch.distributions.constraints.interval(-1.0, 1.0)

add these two lines in __init__ function

**Comment by yusukeurakami** [comment]
@RajGhugare19 thank you for your fix. I will reflect on the next update.
